version: '3.6'

services:
  app:
    build: ./server
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./server:/home/projuser/src
      - /home/projuser/src/.venv
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=madlibs_dev
      - POSTGRES_PASSWORD=madlibs_dev
      - POSTGRES_DB=madlibs_dev
    ports:
      - "5432:5432"
